# Generated by Django 2.1.2 on 2019-01-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_person_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='xmlfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_f', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='people',
        ),
        migrations.DeleteModel(
            name='detail',
        ),
    ]
