# Generated by Django 2.1.2 on 2019-01-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190123_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xmlfiles',
        ),
    ]
